### ISSUE TITLE
Trouble executing profiles

### ISSUE THREAD

**Issue by sp70** [marshall/logcat-color#16]
I've created a '.logcat-color' configuration file, but I'm getting a traceback when attempting to use it.
If I remove the configuration file (or comment everything out), then logcat-color works fine.  I don't know where in the configuration file I'm doing something incorrect.  Am I missing something in the file?  I'm using the configuration example that you provided.  Please help.

The error:
'
$ logcat-color
Traceback (most recent call last):
  File "/usr/bin/logcat-color", line 5, in <module>
    pkg_resources.run_script('logcat-color==0.6.1', 'logcat-color')
  File "/usr/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
  File "/usr/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
  File "/usr/lib/python2.7/site-packages/logcat_color-0.6.1-py2.7.egg/EGG-INFO/scripts/logcat-color", line 252, in <module>
    LogcatColor().loop()
  File "/usr/lib/python2.7/site-packages/logcat_color-0.6.1-py2.7.egg/EGG-INFO/scripts/logcat-color", line 224, in loop
    self.start()
  File "/usr/lib/python2.7/site-packages/logcat_color-0.6.1-py2.7.egg/EGG-INFO/scripts/logcat-color", line 218, in start
    self.start_logcat()
  File "/usr/lib/python2.7/site-packages/logcat_color-0.6.1-py2.7.egg/EGG-INFO/scripts/logcat-color", line 208, in start_logcat
    self.input = Popen(adb_command, stdout=PIPE).stdout
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The .logcat-color configuration file:

# Full path to adb, default is to look at the environment variable ADB, or
# fall back on using "adb" from the system PATH
adb = "/path/to/adb"

# Width of the TAG column, default is 20
tag_width = 20

# Width of the PID column, default is 8
pid_width = 8

# Width of priority (log level) column, default is 3
priority_width = 3

# Whether or not to wrap the message inside a column. Setting this to False
# enables easier copy/paste. default is True
wrap = True

Profile(name = "radio",
    # Specify a custom device
    device = "device_name",

    # Enable both radio and main buffers (-b radio -b main)
    buffers = ("radio", "main"),

    # Only pay attention to the RIL and RILC tags, and give them custom colors
    tags = {
        "RIL": BLUE,
        "RILC": GREEN
    },

    # Only look at these priority levels
    priorities = ("I", "W", "E"),

    # Use threadtime format to get date/time stamps and thread IDs
    format = "threadtime",

    # Some custom filters
    filters = (
      r"My Custom Regex",
      lambda data: data["message"] == "Custom filter"
    ),
)

Profile(name = "CosctoApp",
    packages = [ "com.costco.app.android" ]
)

**Comment by marshall** [comment]
The "/path/to/adb" is just an example, you'll need to pass your real executable path for logcat-color to correctly identify ADB from the Android SDK :)

**Comment by marshall** [comment]
@sp70 I just committed a change that will give you a more useful error if ADB can't be found. were you able to get this working?

**Comment by sp70** [comment]
Hi Marshall,

Yes, I was able to get this working.  I had overlooked the path.  Thank you for identifying this for me.

I'll give your new change a try.

**Comment by marshall** [comment]
Great! I'll close this out.
